import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Toaster } from "sonner";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FinChamp",
  description: "Generated by Tech Titans",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={font.className}>
        <Toaster />
        {children}</body>
    </html>
    </ClerkProvider>
  );
}
